### ISSUE TITLE
previewForm : enable scroll-bars in the modal dialog 

### ISSUE THREAD

**Issue by mehtadiesh** [aniketan/previewForm#1]
hello,

Greetings!!

The plugin was awesome. but Sir My form size is big. so yes/ no button goes down side of the window and scrollbars is not appearing. please tell me how to enable scroll-bars in the modal dialog so that yes/ no button can come up.
my mail id is mehtadinesh@gmail.com

regards,

Dinesh

**Comment by aniketan** [comment]
#previewBox{
height:300px;
overflow-y:scroll;
}
